from __future__ import annotations

from .signals import (
    _aspect,
    _beat_sync,
    _caption_keyword,
    _captions,
    _chapters,
    _comment_prompt,
    _cta_placement,
    _description_depth,
    _description_keyword_zone,
    _duet_stitch,
    _duration_fit,
    _end_screen,
    _hashtag_count,
    _hook,
    _intro_delay,
    _keyword_coverage,
    _loop,
    _measured_distribution,
    _measured_retention,
    _on_screen_text,
    _pacing,
    _playlist,
    _publish_window,
    _repost_watermark,
    _safe_zone,
    _series,
    _sound_trend,
    _Spec,
    _spoken_keyword,
    _tags,
    _thumbnail_present,
    _thumbnail_text,
    _title_cover_complement,
    _title_keyword,
    _title_length,
    _title_style,
    _title_unusable,
)

_YOUTUBE_SPECS: tuple[_Spec, ...] = (
    _Spec(
        "title_keyword", "Search phrase in the title", "search", 0.30, _title_keyword
    ),
    _Spec(
        "title_length",
        "Title length",
        "search",
        0.12,
        _title_length,
        blocking=True,
        blocking_when=_title_unusable,
    ),
    _Spec(
        "description_keyword_zone",
        "Keyword in the opening characters",
        "search",
        0.18,
        _description_keyword_zone,
    ),
    _Spec("description_depth", "Description depth", "search", 0.14, _description_depth),
    _Spec("tags", "Tag set", "search", 0.10, _tags),
    # Hashtags are optional on YouTube (only the first three above the title are
    # shown), so a missing set costs points but never blocks publishing.
    _Spec("hashtags", "Hashtag discipline", "search", 0.10, _hashtag_count),
    _Spec(
        "keyword_coverage", "Target-phrase coverage", "search", 0.06, _keyword_coverage
    ),
    _Spec("chapters", "Chapters / timestamps", "search", 0.08, _chapters),
    _Spec("thumbnail", "Custom thumbnail", "packaging", 0.40, _thumbnail_present),
    _Spec("thumbnail_text", "Cover text", "packaging", 0.20, _thumbnail_text),
    _Spec(
        "title_cover_complement",
        "Title and cover complement each other",
        "packaging",
        0.15,
        _title_cover_complement,
    ),
    _Spec("title_style", "Title craft", "packaging", 0.25, _title_style),
    _Spec("hook", "Hook quality", "retention", 0.25, _hook),
    _Spec("intro_delay", "No dead intro", "retention", 0.10, _intro_delay),
    _Spec("pacing", "Cut rate", "retention", 0.10, _pacing),
    _Spec("cta_placement", "CTA placement", "retention", 0.08, _cta_placement),
    # Runtime is a retention recommendation: four minutes is perfectly
    # publishable, so this signal costs points without capping the score.
    _Spec("duration_fit", "Runtime fit", "retention", 0.12, _duration_fit),
    _Spec(
        "retention_measured",
        "Measured watch time",
        "retention",
        0.20,
        _measured_retention,
    ),
    _Spec("end_screen", "End screen", "distribution", 0.20, _end_screen),
    _Spec("playlist", "Playlist placement", "distribution", 0.18, _playlist),
    _Spec("publish_window", "Publish window", "distribution", 0.22, _publish_window),
    _Spec("comment_prompt", "Comment prompt", "distribution", 0.12, _comment_prompt),
    _Spec("series", "Series continuity", "distribution", 0.14, _series),
    _Spec("aspect", "Aspect ratio", "distribution", 0.14, _aspect, blocking=True),
    _Spec("captions", "Captions", "distribution", 0.10, _captions),
    _Spec(
        "distribution_measured",
        "Measured engagement",
        "distribution",
        0.14,
        _measured_distribution,
    ),
)

_SHORTS_SPECS: tuple[_Spec, ...] = (
    _Spec(
        "title_keyword", "Search phrase in the title", "search", 0.30, _title_keyword
    ),
    _Spec(
        "title_length",
        "Title length",
        "search",
        0.15,
        _title_length,
        blocking=True,
        blocking_when=_title_unusable,
    ),
    _Spec(
        "description_keyword_zone",
        "Keyword in the opening characters",
        "search",
        0.25,
        _description_keyword_zone,
    ),
    _Spec("hashtags", "Hashtag discipline", "search", 0.20, _hashtag_count),
    _Spec("tags", "Tag set", "search", 0.15, _tags),
    _Spec(
        "keyword_coverage", "Target-phrase coverage", "search", 0.10, _keyword_coverage
    ),
    _Spec("hook", "Hook quality", "packaging", 0.35, _hook),
    _Spec("thumbnail_text", "Cover text", "packaging", 0.25, _thumbnail_text),
    _Spec("title_style", "Title craft", "packaging", 0.20, _title_style),
    _Spec("safe_zone", "UI safe zone", "packaging", 0.20, _safe_zone),
    _Spec("duration_fit", "Runtime fit", "retention", 0.22, _duration_fit),
    _Spec("intro_delay", "No dead intro", "retention", 0.18, _intro_delay),
    _Spec("pacing", "Cut rate", "retention", 0.12, _pacing),
    _Spec("loop", "Loopability", "retention", 0.16, _loop),
    _Spec(
        "retention_measured",
        "Measured watch time",
        "retention",
        0.20,
        _measured_retention,
    ),
    _Spec("aspect", "Aspect ratio", "retention", 0.12, _aspect, blocking=True),
    _Spec("captions", "Captions", "distribution", 0.22, _captions),
    _Spec("publish_window", "Publish window", "distribution", 0.24, _publish_window),
    _Spec("comment_prompt", "Comment prompt", "distribution", 0.18, _comment_prompt),
    _Spec("series", "Series continuity", "distribution", 0.16, _series),
    _Spec(
        "distribution_measured",
        "Measured engagement",
        "distribution",
        0.20,
        _measured_distribution,
    ),
)

_TIKTOK_SPECS: tuple[_Spec, ...] = (
    _Spec(
        "caption_keyword",
        "Keyword in the caption opening",
        "discoverability",
        0.30,
        _caption_keyword,
    ),
    _Spec(
        "description_depth",
        "Caption length and substance",
        "discoverability",
        0.16,
        _description_depth,
    ),
    # TikTok captions work without hashtags; the set is scored, not enforced.
    _Spec("hashtags", "Hashtag discipline", "discoverability", 0.20, _hashtag_count),
    _Spec("on_screen_text", "On-screen text", "discoverability", 0.14, _on_screen_text),
    _Spec("spoken_keyword", "Spoken keyword", "discoverability", 0.14, _spoken_keyword),
    _Spec(
        "keyword_coverage",
        "Target-phrase coverage",
        "discoverability",
        0.12,
        _keyword_coverage,
    ),
    _Spec("captions", "Captions", "discoverability", 0.10, _captions),
    _Spec("hook", "Hook quality", "retention", 0.28, _hook),
    _Spec("intro_delay", "No dead intro", "retention", 0.18, _intro_delay),
    _Spec("duration_fit", "Runtime for completion", "retention", 0.16, _duration_fit),
    _Spec("loop", "Loopability", "retention", 0.12, _loop),
    _Spec("pacing", "Cut rate", "retention", 0.10, _pacing),
    _Spec(
        "retention_measured",
        "Measured completion",
        "retention",
        0.22,
        _measured_retention,
    ),
    _Spec("sound_trend", "Trending sound", "sound", 0.45, _sound_trend),
    _Spec("beat_sync", "Beat-synced cuts", "sound", 0.30, _beat_sync),
    _Spec("safe_zone", "UI safe zone", "sound", 0.25, _safe_zone),
    _Spec(
        "repost_watermark",
        "No repost watermark",
        "distribution",
        0.24,
        _repost_watermark,
        blocking=True,
    ),
    _Spec("aspect", "Aspect ratio", "distribution", 0.18, _aspect, blocking=True),
    _Spec("publish_window", "Publish window", "distribution", 0.18, _publish_window),
    _Spec("comment_prompt", "Comment prompt", "distribution", 0.14, _comment_prompt),
    _Spec("duet_stitch", "Duet / stitch open", "distribution", 0.12, _duet_stitch),
    _Spec("series", "Series continuity", "distribution", 0.10, _series),
    _Spec(
        "distribution_measured",
        "Measured engagement",
        "distribution",
        0.18,
        _measured_distribution,
    ),
)

_SPECS: dict[str, tuple[_Spec, ...]] = {
    "youtube": _YOUTUBE_SPECS,
    "youtube_shorts": _SHORTS_SPECS,
    "tiktok": _TIKTOK_SPECS,
}
