"""Assets ingested from outside the pipeline (generated by agents)."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from .common import utcnow


class ExternalAssetType(enum.StrEnum):
    """Classification of external AI and third-party media assets."""

    SCENE_VIDEO = "scene_video"  # Kling, Veo, Wan 2.1, Runway
    SCENE_IMAGE = "scene_image"  # Midjourney, Flux, Stable Diffusion
    VOICEOVER = "voiceover"  # ElevenLabs, OpenAI TTS, Edge-TTS
    BACKGROUND_MUSIC = "background_music"  # Suno AI, Udio, Artlist
    RESEARCH_DOSSIER = "research_dossier"  # Perplexity, DeepResearch
    FACT_CHECK_REPORT = "fact_check_report"  # Fact check synthesis
    SUBTITLE = "subtitle"  # CapCut SRT/VTT


class ExternalImportRequest(BaseModel):
    """Request payload to ingest an external asset into the project."""

    asset_type: ExternalAssetType
    scene_id: str | None = None
    scene_index: int | None = None
    url: str | None = None
    raw_content: str | None = None
    label: str | None = None
    attribution: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExternalAssetRecord(BaseModel):
    """A record of an ingested external asset."""

    id: str
    project_id: str
    asset_type: ExternalAssetType
    scene_id: str | None = None
    url: str | None = None
    filename: str | None = None
    label: str | None = None
    attribution: str | None = None
    created_at: datetime = Field(default_factory=utcnow)


class BatchExternalImportRequest(BaseModel):
    """Batch ingest multiple external assets in a single call."""

    items: list[ExternalImportRequest] = Field(default_factory=list)
